--
-- 启用触发器
--
ALTER TRIGGER TRI_XXL_JOB_INFO_ID ENABLE;
ALTER TRIGGER TRI_XXL_JOB_LOG_ID ENABLE;
ALTER TRIGGER TRI_XXL_JOB_LOG_REPORT_ID ENABLE;
ALTER TRIGGER TRI_XXL_JOB_LOGGLUE_ID ENABLE;
ALTER TRIGGER TRI_XXL_JOB_REGISTRY_ID ENABLE;
ALTER TRIGGER TRI_XXL_JOB_GROUP_ID ENABLE;
ALTER TRIGGER TRI_XXL_JOB_USER_ID ENABLE;
