--
-- 禁用触发器
--
ALTER TRIGGER TRI_XXL_JOB_INFO_ID DISABLE;
ALTER TRIGGER TRI_XXL_JOB_LOG_ID DISABLE;
ALTER TRIGGER TRI_XXL_JOB_LOG_REPORT_ID DISABLE;
ALTER TRIGGER TRI_XXL_JOB_LOGGLUE_ID DISABLE;
ALTER TRIGGER TRI_XXL_JOB_REGISTRY_ID DISABLE;
ALTER TRIGGER TRI_XXL_JOB_GROUP_ID DISABLE;
ALTER TRIGGER TRI_XXL_JOB_USER_ID DISABLE;

--
-- 删除触发器
--
DROP TRIGGER TRI_XXL_JOB_INFO_ID;
DROP TRIGGER TRI_XXL_JOB_LOG_ID;
DROP TRIGGER TRI_XXL_JOB_LOG_REPORT_ID;
DROP TRIGGER TRI_XXL_JOB_LOGGLUE_ID;
DROP TRIGGER TRI_XXL_JOB_REGISTRY_ID;
DROP TRIGGER TRI_XXL_JOB_GROUP_ID;
DROP TRIGGER TRI_XXL_JOB_USER_ID;

--
-- 删除自增序列
--
DROP SEQUENCE SEQ_XXL_JOB_INFO_ID;
DROP SEQUENCE SEQ_XXL_JOB_LOG_ID;
DROP SEQUENCE SEQ_XXL_JOB_LOG_REPORT_ID;
DROP SEQUENCE SEQ_XXL_JOB_LOGGLUE_ID;
DROP SEQUENCE SEQ_XXL_JOB_REGISTRY_ID;
DROP SEQUENCE SEQ_XXL_JOB_GROUP_ID;
DROP SEQUENCE SEQ_XXL_JOB_USER_ID;

--
-- 删除表数据
--
DELETE FROM xxl_job_info;
DELETE FROM xxl_job_log;
DELETE FROM xxl_job_log_report;
DELETE FROM xxl_job_logglue;
DELETE FROM xxl_job_registry;
DELETE FROM xxl_job_group;
DELETE FROM xxl_job_user;
DELETE FROM xxl_job_lock;
COMMIT;

--
-- 删除数据表
--
DROP TABLE xxl_job_info;
DROP TABLE xxl_job_log;
DROP TABLE xxl_job_log_report;
DROP TABLE xxl_job_logglue;
DROP TABLE xxl_job_registry;
DROP TABLE xxl_job_group;
DROP TABLE xxl_job_user;
DROP TABLE xxl_job_lock;
